#端口号
server:
  port: 9201
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password: acadlmp0.
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.1.105/herdsman_center?useUnicode=true&characterEncoding=utf-8&characterEncoding=utf8&serverTimezone=UTC
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*/*.xml